kind: Pod
apiVersion: v1
metadata:
  name: flex-provisioner
spec:
  serviceAccountName: flex-provisioner
  containers:
    - name: flex-provisioner
      image: mandar-dev3.gsintlab.com:5000/flex-provisioner
      securityContext:
      args:
        - "-provisioner=apporbit.com/starling"
        - "-kubeconfig=/etc/apporbit/admin.conf"
        - "-execCommand=/usr/libexec/kubernetes/kubelet-plugins/volume/exec/apporbit~starling/starling"
        - "-flexDriver=apporbit/starling"
      imagePullPolicy: "IfNotPresent"
      volumeMounts:
      - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
        name: flexvolume-dir
      - mountPath: /etc/apporbit
        name: kubeconf-dir
  volumes:
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/apporbit
      type: DirectoryOrCreate
  name: kubeconf-dir
